### ISSUE TITLE
.

### ISSUE THREAD

**Issue by breakcraft** [MeteorLite/hotlite-client#3]

**Comment by zeruth** [comment]
This is a good learning opportunity for you. You should not fork a project you don't intend to contribute to. Just download the code and start a new repo,

**Comment by breakcraft** [comment]
> This is a good learning opportunity for you. You should not fork a project you don't intend to contribute to. Just download the code and start a new repo,

Thanks. I’ll contribute as I continue getting better at consolidating updates. These were misclicks that I didn’t intend to show up on here.
